// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	models "creditlimit-connector/app/models"

	mock "github.com/stretchr/testify/mock"
)

// FnGetOnshoreBusinessDateRepo is an autogenerated mock type for the FnGetOnshoreBusinessDateRepo type
type FnGetOnshoreBusinessDateRepo struct {
	mock.Mock
}

// FindLocalToday provides a mock function with given fields:
func (_m *FnGetOnshoreBusinessDateRepo) FindLocalToday() (models.FnGetOnshoreBusinessDateModel, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindLocalToday")
	}

	var r0 models.FnGetOnshoreBusinessDateModel
	var r1 error
	if rf, ok := ret.Get(0).(func() (models.FnGetOnshoreBusinessDateModel, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() models.FnGetOnshoreBusinessDateModel); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.FnGetOnshoreBusinessDateModel)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFnGetOnshoreBusinessDateRepo creates a new instance of FnGetOnshoreBusinessDateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFnGetOnshoreBusinessDateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FnGetOnshoreBusinessDateRepo {
	mock := &FnGetOnshoreBusinessDateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
