// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SBATlockRepo is an autogenerated mock type for the SBATlockRepo type
type SBATlockRepo struct {
	mock.Mock
}

// FilterValidAccount provides a mock function with given fields: accounts
func (_m *SBATlockRepo) FilterValidAccount(accounts []string) ([]string, error) {
	ret := _m.Called(accounts)

	if len(ret) == 0 {
		panic("no return value specified for FilterValidAccount")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]string, error)); ok {
		return rf(accounts)
	}
	if rf, ok := ret.Get(0).(func([]string) []string); ok {
		r0 = rf(accounts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(accounts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSBATlockRepo creates a new instance of SBATlockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSBATlockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SBATlockRepo {
	mock := &SBATlockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
